export default {
  obj: {
    translations: {
      weekdays: {
        full: [
          'нядзеля',
          'панядзелак',
          'аўторак',
          'серада',
          'чацвер',
          'пятніца',
          'субота',
        ],
        short: [
          'нд',
          'пн',
          'аў',
          'ср',
          'чц',
          'пт',
          'сб',
        ],
      },
      monthes: {
        full: [
          'студзеня',
          'лютага',
          'сакавіка',
          'красавіка',
          'мая',
          'чэрвеня',
          'ліпеня',
          'жніўня',
          'верасня',
          'кастрычніка',
          'лістапада',
          'снежні',
        ],
      },
      placeholderText: {
        en: 'Search city...',
        ru: 'Искать город...',
        be: 'Шукаць горад...',
      },
      searchButtonText: {
        en: 'Search',
        ru: 'Найти',
        be: 'Шукаць',
      },
      serviceText: {
        en: {
          overall: 'the weather for now for',
          deg: 'degrees',
          percent: 'percents',
          feels: 'Feels like',
          wind: 'Wind',
          humidity: 'Humidity',
          vel: {
            M: 'm/s',
            I: 'mph',
          },
          latitude: 'latitude',
          longitude: 'longitude',
        },
        ru: {
          overall: 'Погода сейчас в',
          deg: 'градусов',
          percent: 'процентов',
          feels: 'По ощущению',
          wind: 'Ветер',
          humidity: 'Влажность',
          vel: {
            M: 'м/с',
            I: 'м/ч',
          },
          latitude: 'широта',
          longitude: 'долгота',
        },
        be: {
          overall: 'надворе зараз в',
          deg: 'градусаў',
          percent: 'працэнтау',
          feels: 'АДЧУВАЕЦЦА ЯК',
          wind: 'ВЕЦЕР',
          humidity: 'ВІЛЬГОТНАСЦЬ',
          vel: {
            M: 'м/с',
            I: 'м/ч',
          },
          latitude: 'Шырата',
          longitude: 'Даўгата',
        },
      },
    },
  },
};
